# Korjaa jäljellä olevat englanninkieliset kommentit PIPE-tiedostoista
$pipe = "c:\database_migration\Access\PIPE\"

$replacements = @{
  "' Connect to AutoCAD" = "' Yhdistetään AutoCADiin"
  "' Build SQL query" = "' Rakennetaan SQL-kysely"
  "' Create selection set" = "' Luodaan valintajoukko"
  "' Try to connect to running AutoCAD" = "' Yhdistetään käynnissä olevaan AutoCADiin"
  "' Process all valves" = "' Käsitellään kaikki venttiilit"
  "' Open new drawing if changed" = "' Avataan uusi piirustus, jos DWG-tiedosto muuttuu"
  "' Process valve if valid" = "' Käsitellään venttiili, jos tiedot ovat kelvolliset"
  "' Copy attributes" = "' Kopioidaan attribuutit"
  "' Silent error - don't interrupt user" = "' Hiljainen virhe - ei keskeytä käyttäjää"
  "' Check if link path differs from current database path" = "' Tarkistetaan, eroaako linkkipolku nykyisestä tietokantapolusta"
  "' Tarkoitus: Pipeline segment selector for multi-segment pipelines" = "' Tarkoitus: Monisegmenttisten putkilinjojen segmentinvalitsin"
  "'   When a pipeline spans multiple drawings, this form allows selection:" = "'   Kun putkilinja ulottuu useisiin piirustuksiin, tällä lomakkeella valitaan segmentti:"
  "'   - Displays list of pipeline segments from PIPELINEDATA" = "'   - Näyttää putkilinjasegmenttien listan PIPELINEDATA-taulukosta"
  "'   - Shows path, drawing, area, line, FROM, TO for each segment" = "'   - Näyttää polun, piirustuksen, alueen, linjan, FROM ja TO kullekin segmentille"
  "'   - Auto-opens if only 2 segments (one is header row)" = "'   - Avautuu automaattisesti, jos vain 2 segmenttiä (yksi on otsikkorivi)"
  "'   - PIPELINEDATA table (imported pipeline data)" = "'   - PIPELINEDATA-taulukko (tuotu putkilinjadata)"
  "'   - AvaaKuvasta function from Koodit module" = "'   - AvaaKuvasta-funktio Koodit-moduulista"
  "' OpenArgs Format:" = "' OpenArgs-muoto:"
  "'   - Lista: Listbox showing pipeline segments" = "'   - Lista: Listaruutu putkilinjasegmenteille"
  "'   - Command3: Open selected button" = "'   - Command3: Avaa valittu -painike"
  "'   - Command4: Close form button" = "'   - Command4: Sulje lomake -painike"
  "'   1. Parse OpenArgs for AreaCode and LineNo" = "'   1. Jäsennetään OpenArgs (aluekoodi ja linjanumero)"
  "'   2. Build SQL to query PIPELINEDATA for matching segments" = "'   2. Rakennetaan SQL-kysely PIPELINEDATA-taulukkoon"
  "'   3. Populate Lista listbox with results" = "'   3. Täytetään Lista-listaruutu tuloksilla"
  "'   4. If only 2 rows (header + 1 segment), auto-open and close" = "'   4. Jos vain 2 riviä (otsikko + 1 segmentti), avataan automaattisesti"
  "'   5. If no data found, show error and close" = "'   5. Jos dataa ei löydy, näytetään virhe ja suljetaan"
  "'   - Must be opened via OpenArgs with" = "'   - Avattava OpenArgs-parametrilla muotoiltuna"
  "'   - Auto-selects first segment (row 1)" = "'   - Valitsee ensimmäisen segmentin automaattisesti (rivi 1)"
  "'   - Shows error if opened incorrectly" = "'   - Näyttää virheen, jos lomake avataan väärin"
  "'   Sulje - Boolean, True = close form after opening" = "'   Sulje - Boolean, True = suljetaan lomake avauksen jälkeen"
  "'   1. Extract selected row data from Lista listbox" = "'   1. Poimitaan valitun rivin tiedot Lista-listaruudusta"
  "'   2. Get PATH, ImpFileID (drawing), Handles, identification info" = "'   2. Haetaan polku, piirustus, Handle ja tunnistetiedot"
  "'   3. Call AvaaKuvasta to open drawing and zoom to block" = "'   3. Kutsutaan AvaaKuvasta avaamaan piirustus ja zoomaamaan blokkiin"
  "'   4. Optionally close form" = "'   4. Suljetaan lomake tarvittaessa"
  "'   - Lista.ListIndex is 0-based, so add 1 to skip header" = "'   - Lista.ListIndex on 0-pohjainen, lisätään 1 otsikon ohittamiseksi"
  "'   - Column indices: 0=PATH, 1=ImpFileID, 2=Handles, 3=DEP, 5=LINENO" = "'   - Sarakeindeksit: 0=PATH, 1=ImpFileID, 2=Handles, 3=DEP, 5=LINENO"
  "'   1. Connect to running AutoCAD (Yhdista function)" = "'   1. Yhdistetään käynnissä olevaan AutoCADiin (Yhdista-funktio)"
  "'   2. Delete any existing APUPICK selection set" = "'   2. Poistetaan olemassa oleva APUPICK-valintajoukko"
  "'   3. Create new selection set with flow block filter" = "'   3. Luodaan uusi valintajoukko virtausblokkiluodatilla"
  "'   4. Display first block" = "'   4. Näytetään ensimmäinen blokki"
  "'   - Closes form if AutoCAD not running" = "'   - Suljetaan lomake, jos AutoCAD ei ole käynnissä"
  "'   - Closes form if no flow blocks found" = "'   - Suljetaan lomake, jos virtausblokkeja ei löydy"
  "'   - Filter: PDUFLOWDATA, ARAFLOW, FLOWBLOCK, BALANCE_DATA block types" = "'   - Suodatin: PDUFLOWDATA, ARAFLOW, FLOWBLOCK, BALANCE_DATA -blokit"
  "'   1. For each flow block in selection set" = "'   1. Käydään läpi jokainen virtausblokki valintajoukossa"
  "'   2. Call EtsiLinja to auto-find pipeline near block" = "'   2. Kutsutaan EtsiLinja etsimään läheisin putkilinja"
  "'   3. Track if any pipelines not found" = "'   3. Seurataan, löytyikö kaikille blokeille putkilinja"
  "'   4. Display summary message" = "'   4. Näytetään yhteenviesti"
  "'   - Iterates through all blocks automatically" = "'   - Käy automaattisesti läpi kaikki blokit"
  "'   - Sets EiLinjaa flag if pipeline not found for any block" = "'   - Asettaa EiLinjaa-lipun, jos jollekin blokille ei löydy putkilinjaa"
  "'   1. Activate AutoCAD window" = "'   1. Aktivoidaan AutoCAD-ikkuna"
  "'   2. Prompt user to pick pipeline block" = "'   2. Pyydetään käyttäjää poimiman putkilinjablokki"
  "'   3. Extract pipeline reference from block attributes" = "'   3. Poimitaan putkilinjaviittaus blokin attribuuteista"
  "'   4. Update current flow block's pipeline attribute" = "'   4. Päivitetään nykyisen virtausblokin putkilinja-attribuutti"
  "'   - Works with PIPELINE, PIPELINE_F, ARAPIPEL, BAHPIPEL, METSO_PIPE blocks" = "'   - Toimii PIPELINE, PIPELINE_F, ARAPIPEL, BAHPIPEL, METSO_PIPE -blokkien kanssa"
  "'   - Falls back to POS.NO, CUSTPOS, SDPOS attributes for other blocks" = "'   - Käyttää POS.NO, CUSTPOS, SDPOS -attribuutteja muille blokeille"
  "'   - Uses AttribToPipeline helper for standard pipeline blocks" = "'   - Käyttää AttribToPipeline-apufunktiota standardiputkilinjoille"
  "'   Attrib - Array of block attributes from GetAttributes" = "'   Attrib - GetAttributes-funktion palauttama attribuuttitaulukko"
  "' Palautusarvo: String - Formatted pipeline reference (DEP & FSB & LINE)" = "' Palautusarvo: Merkkijono - muotoiltu putkilinjaviittaus (DEP & FSB & LINE)"
  "'   1. Scan attributes for DEP/DEPA, FSB, LINE tags" = "'   1. Skannataan attribuutit: DEP/DEPA, FSB, LINE -tagit"
  "'   2. Concatenate values without delimiters" = "'   2. Yhdistetään arvot ilman erotinmerkkejä"
  "'   - Handles both DEP and DEPA attribute tags" = "'   - Käsittelee sekä DEP- että DEPA-attribuuttitagit"
  "'   1. Unhighlight current block" = "'   1. Poistetaan nykyisen blokin korostus"
  "'   2. Move to next block" = "'   2. Siirrytään seuraavaan blokkiin"
  "'   3. Check if pipeline reference is empty" = "'   3. Tarkistetaan, onko putkilinjaviittaus tyhjä"
  "'   4. Repeat until empty found or all blocks checked" = "'   4. Toistetaan, kunnes tyhjä löytyy tai kaikki blokit on käyty"
  "'   - Skips blocks that already have pipeline reference" = "'   - Ohitetaan blokit, joilla on jo putkilinjaviittaus"
  "'   - Stops at first empty block found" = "'   - Pysähdytään ensimmäiseen tyhjään blokkiin"
  "'   - Wraps to last block if at beginning" = "'   - Siirtyy viimeiseen blokkiin, jos ollaan alussa"
  "'   - Wraps to first block if at end" = "'   - Siirtyy ensimmäiseen blokkiin, jos ollaan lopussa"
  "'   1. Highlight current block in selection set" = "'   1. Korostetaan nykyinen blokki valintajoukossa"
  "'   2. Update form caption with block count" = "'   2. Päivitetään lomakkeen otsikko blokkimäärällä"
  "'   3. Zoom to block location" = "'   3. Zoomataan blokin sijaintiin"
  "'   4. Find and set pipeline attribute reference" = "'   4. Etsitään ja asetetaan putkilinja-attribuuttiviittaus"
  "'   5. Display current pipeline value in TRefNo" = "'   5. Näytetään nykyinen putkilinja-arvo TRefNo-kentässä"
  "'   - Searches for PIPEREF, PIPELINENO, or PIPE_LINE attribute" = "'   - Etsii PIPEREF-, PIPELINENO- tai PIPE_LINE-attribuutin"
  "'   - Shows error if attribute not found" = "'   - Näyttää virheen, jos attribuuttia ei löydy"
  "' Palautusarvo: Boolean - True if connected, False if AutoCAD not running" = "' Palautusarvo: Boolean - True jos yhteys onnistui, False jos AutoCAD ei käynnissä"
  "'   1. Try GetObject to connect to running AutoCAD" = "'   1. Kokeillaan GetObject-yhteys käynnissä olevaan AutoCADiin"
  "'   2. If successful, set oDOC to active document" = "'   2. Jos onnistui, asetetaan oDOC aktiiviseen piirustukseen"
  "'   3. Return connection status" = "'   3. Palautetaan yhteystila"
  "'   - Called from Form_Load" = "'   - Kutsutaan Form_Load-tapahtumasta"
  "'   - Sets module-level oACAD and oDOC variables" = "'   - Asettaa moduulitason oACAD- ja oDOC-muuttujat"
  "'   1. Get current flow block insertion point" = "'   1. Haetaan nykyisen virtausblokin sijainti"
  "'   2. Define search window (56 units right, 13 units up from block)" = "'   2. Määritetään hakuikkuna (56 yks. oikealle, 13 yks. ylös)"
  "'   3. Create selection set with pipeline block filter" = "'   3. Luodaan valintajoukko putkilinjablokkiluodatilla"
  "'   4. If pipeline found, extract reference and update flow block" = "'   4. Jos putkilinja löytyy, poimitaan viittaus ja päivitetään blokki"
  "'   5. If not found, clear attribute and set EiLinjaa flag" = "'   5. Jos ei löydy, tyhjennetään attribuutti ja asetetaan EiLinjaa"
  "'   - Searches for PIPELINE, BAHPIPEL, ARAPIPEL blocks" = "'   - Etsii PIPELINE, BAHPIPEL, ARAPIPEL -blokkeja"
  "'   - Uses crossing window selection" = "'   - Käyttää leikkausikkunavalintaa"
  "'   - Deletes temporary selection set after use" = "'   - Poistaa tilapäisen valintajoukon käytön jälkeen"
  "'   - Sets EiLinjaa=True if no pipeline found" = "'   - Asettaa EiLinjaa=True, jos putkilinjaa ei löydy"
  "' Tarkoitus: Update AutoCAD block attribute when user edits pipeline reference" = "' Tarkoitus: Päivittää AutoCAD-blokin attribuutin, kun käyttäjä muokkaa viittausta"
  "'   - Uses Nz to handle null values" = "'   - Käyttää Nz-funktiota Null-arvojen käsittelyyn"
  "'   Attrib - Array of block attributes" = "'   Attrib - Blokin attribuuttitaulukko"
  "'   Teksti - TextBox to populate with reference value" = "'   Teksti - Tekstikenttä, johon viittaus asetetaan"
  "'   oAttrib - Attribute reference to update" = "'   oAttrib - Päivitettävä attribuuttiviittaus"
  "'   VJoukko - Selection set object to create" = "'   VJoukko - Luotava valintajoukko-objekti"
  "' Palautusarvo: True if connection successful, False otherwise" = "' Palautusarvo: True jos yhteys onnistui, False muuten"
  "' Palautusarvo: Concatenated pipeline reference string" = "' Palautusarvo: Yhdistetty putkilinjaviittausmerkkijono"
  "'   - Delete if already exists" = "'   - Poistetaan, jos on jo olemassa"
  "' Tarkoitus: Automatically find pipelines for all flow blocks" = "' Tarkoitus: Löytää automaattisesti kaikki putkilinjat virtausblokeille"
  "' Tarkoitus: Pick pipeline from AutoCAD drawing by clicking on block" = "' Tarkoitus: Poimii putkilinjan AutoCAD-piirustuksesta klikkaamalla blokkia"
  "' Tarkoitus: Extract pipeline reference from pipeline block attributes" = "' Tarkoitus: Poimii putkilinjaviittauksen putkilinjablokin attribuuteista"
  "' Tarkoitus: Find next flow block with empty pipeline reference" = "' Tarkoitus: Etsii seuraavan virtausblokin, jolla putkilinjaviittaus on tyhjä"
  "' Tarkoitus: Navigate to previous flow block" = "' Tarkoitus: Navigoi edelliseen virtausblokkiin"
  "' Tarkoitus: Navigate to next flow block" = "' Tarkoitus: Navigoi seuraavaan virtausblokkiin"
  "' Tarkoitus: Close form" = "' Tarkoitus: Sulkee lomakkeen"
  "' Tarkoitus: Display and zoom to current flow block in AutoCAD" = "' Tarkoitus: Näyttää ja zoomaa nykyisen virtausblokin AutoCADissa"
  "' Tarkoitus: Connect to running AutoCAD instance" = "' Tarkoitus: Yhdistää käynnissä olevaan AutoCAD-instanssiin"
  "' Tarkoitus: Automatically find pipeline near current flow block" = "' Tarkoitus: Etsii automaattisesti putkilinjan lähellä nykyistä virtausblokkia"
  "' Tarkoitus: Close the form" = "' Tarkoitus: Sulkee lomakkeen"
  "' Tarkoitus: Pick a pipeline, tank, pump, or equipment from drawing and extract reference" = "' Tarkoitus: Poimii putkilinjan, säiliön, pumpun tai laitteen piirroksesta ja palauttaa viittauksen"
  "' Tarkoitus: Extract pipeline reference from block attributes (DEP+FSB+LINE)" = "' Tarkoitus: Poimii putkilinjaviittauksen blokin attribuuteista (DEP+FSB+LINE)"
  "' Tarkoitus: Find next pipeline block with empty FROM or TO attribute" = "' Tarkoitus: Etsii seuraavan putkilinjablokin, jolla FROM tai TO on tyhjä"
  "' Tarkoitus: Navigate to next pipeline block" = "' Tarkoitus: Navigoi seuraavaan putkilinjan blokkiin"
  "' Tarkoitus: Navigate to previous pipeline block" = "' Tarkoitus: Navigoi edelliseen putkilinjan blokkiin"
  "' Tarkoitus: Move to previous block in selection set (wraps to last)" = "' Tarkoitus: Siirtyy edelliseen blokkiin valintajoukossa (kiertää loppuun)"
  "' Tarkoitus: Clean up AutoCAD objects when form closes" = "' Tarkoitus: Siivotaan AutoCAD-objektit lomakkeen sulkeutuessa"
  "' Tarkoitus: Initialize form, connect to AutoCAD, filter pipeline blocks" = "' Tarkoitus: Alustetaan lomake, yhdistetään AutoCADiin, suodatetaan putkilinjablokit"
  "' Tarkoitus: Create or recreate a named selection set" = "' Tarkoitus: Luo tai uudelleenluo nimetty valintajoukko"
  "' Tarkoitus: Display and highlight current pipeline block, load attributes" = "' Tarkoitus: Näyttää ja korostaa nykyisen putkilinjablokin ja lataa attribuutit"
  "' Tarkoitus: Update FROM attribute when text box value changes" = "' Tarkoitus: Päivittää FROM-attribuutin tekstikentän arvon muuttuessa"
  "' Tarkoitus: Update TO attribute when text box value changes" = "' Tarkoitus: Päivittää TO-attribuutin tekstikentän arvon muuttuessa"
  "' Tarkoitus: Pick pipeline or plate block from drawing and extract reference" = "' Tarkoitus: Poimii putkilinja- tai levyblokin piirroksesta ja palauttaa viittauksen"
  "' Tarkoitus: Find next equipment block with empty PIPELINE attribute" = "' Tarkoitus: Etsii seuraavan laiteblokin, jolla PIPELINE-attribuutti on tyhjä"
  "' Tarkoitus: Navigate to next equipment block" = "' Tarkoitus: Navigoi seuraavaan laitteen blokkiin"
  "' Tarkoitus: Move to next block in selection set (wraps to first)" = "' Tarkoitus: Siirtyy seuraavaan blokkiin valintajoukossa (kiertää alkuun)"
  "' Tarkoitus: Navigate to previous equipment block" = "' Tarkoitus: Navigoi edelliseen laitteen blokkiin"
  "' Tarkoitus: Write text to attribute reference" = "' Tarkoitus: Kirjoittaa tekstin attribuuttiviittaukseen"
  "' Tarkoitus: Pick pipeline reference from AutoCAD drawing" = "' Tarkoitus: Poimii putkilinjaviittauksen AutoCAD-piirustuksesta"
  "' Tarkoitus: Initialize form, connect to AutoCAD, filter equipment blocks" = "' Tarkoitus: Alustetaan lomake, yhdistetään AutoCADiin, suodatetaan laiteblokit"
  "' Tarkoitus: Display and highlight current equipment block, load PIPELINE attribute" = "' Tarkoitus: Näyttää ja korostaa nykyisen laiteblokin ja lataa PIPELINE-attribuutin"
  "' Tarkoitus: Update PIPELINE attribute when text box value changes" = "' Tarkoitus: Päivittää PIPELINE-attribuutin tekstikentän arvon muuttuessa"
  "' Tarkoitus: Open selected pipeline segment" = "' Tarkoitus: Avaa valittu putkilinjasegmentti"
  "' Tarkoitus: Initialize form and populate pipeline segment list" = "' Tarkoitus: Alustetaan lomake ja täytetään putkilinjasegmenttilista"
  "' Tarkoitus: Open selected pipeline segment in AutoCAD" = "' Tarkoitus: Avaa valittu putkilinjasegmentti AutoCADissa"
  "' Tarkoitus: Execute batch valve block replacement" = "' Tarkoitus: Käynnistää venttiilienvaihdon eräajon"
  "' Tarkoitus: Clear FROM attribute of current pipeline block" = "' Tarkoitus: Tyhjentää nykyisen putkilinjablokin FROM-attribuutin"
  "' Tarkoitus: Clear TO attribute of current pipeline block" = "' Tarkoitus: Tyhjentää nykyisen putkilinjablokin TO-attribuutin"
  "' Tarkoitus: Cleanup AutoCAD selection set when form closes" = "' Tarkoitus: Siivotaan AutoCAD-valintajoukko lomakkeen sulkeutuessa"
  "'   - Wraps to last if at beginning" = "'   - Siirtyy viimeiseen, jos ollaan alussa"
  "'   - Wraps to first if at end" = "'   - Siirtyy ensimmäiseen, jos ollaan lopussa"
}

$count = 0
Get-ChildItem "$pipe*.cls","$pipe*.bas" | ForEach-Object {
  $content = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8)
  $changed = $false
  foreach ($key in $replacements.Keys) {
    if ($content.Contains($key)) {
      $content = $content.Replace($key, $replacements[$key])
      $changed = $true
      $count++
    }
  }
  if ($changed) {
    [System.IO.File]::WriteAllText($_.FullName, $content, [System.Text.Encoding]::UTF8)
    Write-Host "Paivitetty: $($_.Name)"
  }
}
Write-Host "Valmis. Yhteensa $count korvata."
